version: "3.3"

services:
  database:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=demo_dev
    ports:
      - "5432:5432"
